---
- hosts: all
  gather_facts: no
  tasks:
    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ curdir }}/nvim/init.vim"
        dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
        state: link
      become: yes

