---
- hosts: all
  vars:
    autoload_path: ~/.local/share/nvim/site/autoload
  gather_facts: no
  tasks:
    - file:
        dest: ~/.config/nvim
        state: directory

    - pip:
        name: neovim
        state: latest
      become: yes

    - file:
        path: "{{ autoload_path }}"
        state: directory
        recurse: yes
      with_items:
        - autoload

    - get_url:
        force: yes
        dest: "{{ autoload_path }}/plug.vim"
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

    - composer:
        global_command: true
        command: require
        arguments: "{{ item }}"
      ignore_errors: true
      become: true
      with_items:
        - "squizlabs/php_codesniffer"
        - "phpmd/phpmd"
        - "felixfbecker/language-server"
