---
- hosts: all
  vars:
    autoload_path: ~/.local/share/nvim/site/autoload
  gather_facts: no
  tasks:
    - file:
        dest: ~/.config/nvim
        state: directory

    - pip:
        name: neovim
        state: latest
      become: yes

    - file:
        path: "{{ autoload_path }}"
        state: directory
        recurse: yes
      with_items:
        - autoload

    - get_url:
        force: yes
        dest: "{{ autoload_path }}/plug.vim"
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
